addLayer('A', {
	name: 'Achievements',
	symbol: 'A',
	position: 0,
	startData() { return {
		unlocked: true,
		points: new Decimal(0),
	}},
	color: '#A5BCC2',
	resource: 'achievements',
	row: 'side',
	layerShown() { return true },
	effectDescription() {
		let text = ['<br>which are multiplying your point ', '', '', ''];
		if (hasUpgrade('ds', 21)) {
			if (hasUpgrade('ds', 24)) text[0] += 'and essence gain by <h2 class="layer-A">' + format(player.A.points.mul(0.2)) + '</h2>x';
			else {
				text[0] += 'gain by <h2 class="layer-A">' + format(player.A.points.mul(0.1).add(1)) + '</h2>x';
				text[1] += 'essence gain by <h2 class="layer-A">' + format(player.A.points.mul(0.2)) + '</h2>x';
			};
			if (hasUpgrade('ds', 23) && !hasUpgrade('ds', 24) && !hasUpgrade('p', 31)) text[2] += 'core and quark gain by <h2 class="layer-A">' + format(player.A.points.pow(2).div(100)) + '</h2>x';
			if (hasUpgrade('ds', 23) && hasUpgrade('ds', 24) && !hasUpgrade('p', 31)) text[1] += 'core and quark gain by <h2 class="layer-A">' + format(player.A.points.pow(2).div(100)) + '</h2>x';
			if (hasUpgrade('ds', 23) && hasUpgrade('ds', 24) && hasUpgrade('p', 31)) text[1] += 'core, prayer, and quark gain by <h2 class="layer-A">' + format(player.A.points.pow(2).div(100)) + '</h2>x';
		} else text[0] += 'gain by <h2 class="layer-A">' + format(player.A.points.mul(0.1).add(1)) + '</h2>x';
		if (hasUpgrade('a', 51)) text[3] += 'subatomic particle gain by <h2 class="layer-A">' + format(player.A.points.pow(1.25)) + '</h2>x';
		if (player.nerdMode) {
			if (hasUpgrade('ds', 21)) {
				if (hasUpgrade('ds', 24)) text[0] += ' (formula: x*0.2)';
				else {
					text[0] += ' (formula: x*0.1+1)';
					text[1] += ' (formula: x*0.2)';
				};
				if (hasUpgrade('ds', 23) && !hasUpgrade('ds', 24) && !hasUpgrade('p', 31)) text[2] += ' (formula: (x^2)/100)';
				if (hasUpgrade('ds', 23) && hasUpgrade('ds', 24)) text[1] += ' (formula: (x^2)/100)';
			} else text[0] += ' (formula: x*0.1+1)';
			if (hasUpgrade('a', 51)) text[3] += ' (formula: x^1.25)';
		};
		let fintext = text[0];
		if (text[1]) fintext += '<br>and also multiplying ' + text[1];
		if (text[2]) fintext += '<br>additionally, also multiplying ' + text[2];
		if (text[3]) fintext += '<br>and lastly, also multiplying ' + text[3];
		return fintext;
	},
	update(diff) {
		player.A.points = new Decimal(player.A.achievements.length);
	},
	tabFormat: [
		"main-display",
		"achievements",
	],
	achievements: {
		11: {
			name: 'The Point',
			done() {return player.points.gte(1)},
			tooltip: 'obtain 1 point.',
			image() { if (hasAchievement('A', 11)) return "images/achievements/11.png" },
			color: '#DFDFDF',
		},
		12: {
			name: 'Very Pointy',
			done() {return player.points.gte(1e10)},
			tooltip: 'obtain 1e10 points.',
			unlocked() { return hasAchievement('A', 11) },
			image() { if (hasAchievement('A', 12)) return "images/achievements/12.png" },
			color: '#DFDFDF',
		},
		13: {
			name: 'Now That\'s Really Pointy',
			done() {return player.points.gte(1e100)},
			tooltip: 'obtain 1e100 points.',
			unlocked() { return hasAchievement('A', 12) },
			image() { if (hasAchievement('A', 13)) return "images/achievements/13.png" },
			color: '#DFDFDF',
		},
		14: {
			name: 'Cosmic Point',
			done() {return player.points.gte('1e1000')},
			tooltip: 'obtain 1e1000 points.',
			unlocked() { return hasAchievement('A', 13) },
			image() { if (hasAchievement('A', 14)) return "images/achievements/14.png" },
			color: '#DFDFDF',
		},
		15: {
			name: 'Everything is Points',
			done() {return player.points.gte('1e10000')},
			tooltip: 'obtain 1e10,000 points.',
			unlocked() { return hasAchievement('A', 14) },
			image() { if (hasAchievement('A', 15)) return "images/achievements/15.png" },
			color: '#DFDFDF',
		},
		16: {
			name: 'Dull Points',
			done() {return player.points.gte(1e10) && player.e.total.eq(0)},
			tooltip: 'obtain 1e10 points with no essence.',
			unlocked() { return hasAchievement('A', 12) && hasAchievement('A', 21) },
			image() { if (hasAchievement('A', 16)) return "images/achievements/16.png" },
			color: '#DFDFDF',
		},
		21: {
			name: 'Essence of Rat',
			done() {return player.e.points.gte(1)},
			tooltip: 'obtain 1 essence.',
			unlocked() { return hasAchievement('A', 21) },
			image() { if (hasAchievement('A', 21)) return "images/achievements/21.png" },
			color: '#4CED13',
		},
		22: {
			name: 'Essence Cluster',
			done() {return player.e.points.gte(1e10)},
			tooltip: 'obtain 1e10 essence.',
			unlocked() { return hasAchievement('A', 21) },
			image() { if (hasAchievement('A', 22)) return "images/achievements/22.png" },
			color: '#4CED13',
		},
		23: {
			name: 'Gleaming, Golden Essence',
			done() {return player.e.points.gte(1e100)},
			tooltip: 'obtain 1e100 essence.',
			unlocked() { return hasAchievement('A', 22) },
			image() { if (hasAchievement('A', 23)) return "images/achievements/23.png" },
			color: '#4CED13',
		},
		24: {
			name: 'Essence of the Universe',
			done() {return player.e.points.gte('1e1000')},
			tooltip: 'obtain 1e1000 essence.',
			unlocked() { return hasAchievement('A', 23) },
			image() { if (hasAchievement('A', 24)) return "images/achievements/24.png" },
			color: '#4CED13',
		},
		25: {
			name: 'Essence of all Essence',
			done() {return player.e.points.gte('1e10000')},
			tooltip: 'obtain 1e10,000 essence.',
			unlocked() { return hasAchievement('A', 24) },
			image() { if (hasAchievement('A', 25)) return "images/achievements/25.png" },
			color: '#4CED13',
		},
		26: {
			name: 'Empty Soul',
			done() {return player.e.points .gte(1e10) && getBuyableAmount('e', 11).eq(0) && getBuyableAmount('e', 12).eq(0)},
			tooltip: 'obtain 1e10 essence with no essence rebuyables.',
			unlocked() { return hasAchievement('A', 22) && hasAchievement('A', 31) },
			image() { if (hasAchievement('A', 26)) return "images/achievements/26.png" },
			color: '#4CED13',
		},
		31: {
			name: 'Cracked Core',
			done() {return player.c.points.gte(1)},
			tooltip: 'obtain 1 core.',
			unlocked() { return hasAchievement('A', 31) },
			image() { if (hasAchievement('A', 31)) return "images/achievements/31.png" },
			color: '#D2D237',
		},
		32: {
			name: 'Mountainous Core',
			done() {return player.c.points.gte(1e10)},
			tooltip: 'obtain 1e10 cores.',
			unlocked() { return hasAchievement('A', 31) },
			image() { if (hasAchievement('A', 32)) return "images/achievements/32.png" },
			color: '#D2D237',
		},
		33: {
			name: 'Core of the Earth',
			done() {return player.c.points.gte(1e100)},
			tooltip: 'obtain 1e100 cores.',
			unlocked() { return hasAchievement('A', 32) },
			image() { if (hasAchievement('A', 33)) return "images/achievements/33.png" },
			color: '#D2D237',
		},
		34: {
			name: 'Core of the Sun',
			done() {return player.c.points.gte('1e1000')},
			tooltip: 'obtain 1e1000 cores.',
			unlocked() { return hasAchievement('A', 33) },
			image() { if (hasAchievement('A', 34)) return "images/achievements/34.png" },
			color: '#D2D237',
		},
		35: {
			name: 'Core of the Universe',
			done() {return player.c.points.gte('1e10000')},
			tooltip: 'obtain 1e10,000 cores.',
			unlocked() { return hasAchievement('A', 34) },
			image() { if (hasAchievement('A', 34)) return "images/achievements/35.png" },
			color: '#D2D237',
		},
		36: {
			name: 'Pointless Core',
			done() {return player.c.points.gte(1e10) && getBuyableAmount('c', 11).eq(0) && getBuyableAmount('c', 12).eq(0) && player.q.total.eq(0)},
			tooltip: 'obtain 1e10 cores with no core rebuyables and quarks.',
			unlocked() { return hasAchievement('A', 32) && hasAchievement('A', 41) },
			image() { if (hasAchievement('A', 36)) return "images/achievements/36.png" },
			color: '#D2D237',
		},
		41: {
			name: 'The Smallest Quark',
			done() {return player.q.points.gte(1)},
			tooltip: 'obtain 1 quark.',
			unlocked() { return hasAchievement('A', 41) },
			image() { if (hasAchievement('A', 41)) return "images/achievements/41.png" },
			color: '#DB5196',
		},
		42: {
			name: 'Quark Field',
			done() {return player.q.points .gte(1e10)},
			tooltip: 'obtain 1e10 quarks.',
			unlocked() { return hasAchievement('A', 41) },
			image() { if (hasAchievement('A', 42)) return "images/achievements/42.png" },
			color: '#DB5196',
		},
		43: {
			name: 'Oh, the Quark of it all',
			done() {return player.q.points.gte(1e100)},
			tooltip: 'obtain 1e100 quarks.',
			unlocked() { return hasAchievement('A', 42) },
			image() { if (hasAchievement('A', 43)) return "images/achievements/43.png" },
			color: '#DB5196',
		},
		44: {
			name: 'Quirky Quarks',
			done() {return player.q.points.gte('1e1000')},
			tooltip: 'obtain 1e1000 quarks.',
			unlocked() { return hasAchievement('A', 43) },
			image() { if (hasAchievement('A', 44)) return "images/achievements/44.png" },
			color: '#DB5196',
		},
		45: {
			name: 'Impossible Quarks',
			done() {return player.q.points.gte('1e10000')},
			tooltip: 'obtain 1e10,000 quarks.',
			unlocked() { return hasAchievement('A', 44) },
			image() { if (hasAchievement('A', 45)) return "images/achievements/45.png" },
			color: '#DB5196',
		},
		46: {
			name: 'The Outside',
			done() {return player.q.points.gte(1e10) && player.c.total.eq(0)},
			tooltip: 'obtain 1e10 quarks with no cores.',
			unlocked() { return hasAchievement('A', 42) && hasAchievement('A', 51) },
			image() { if (hasAchievement('A', 46)) return "images/achievements/46.png" },
			color: '#DB5196',
		},
		51: {
			name: 'Submarine, Subatomic',
			done() {return player.sp.points.gte(1)},
			tooltip: 'obtain 1 subatomic particle.',
			unlocked() { return hasAchievement('A', 51) },
			image() { if (hasAchievement('A', 51)) return "images/achievements/51.png" },
			color: '#710CC4',
		},
		52: {
			name: 'Variant Particles',
			done() {return player.sp.points.gte(100)},
			tooltip: 'obtain 100 subatomic particles.',
			unlocked() { return hasAchievement('A', 51) },
			image() { if (hasAchievement('A', 52)) return "images/achievements/52.png" },
			color: '#710CC4',
		},
		53: {
			name: 'Periodic Particles',
			done() {return player.sp.points.gte(10000)},
			tooltip: 'obtain 10,000 subatomic particles.',
			unlocked() { return hasAchievement('A', 52) },
			image() { if (hasAchievement('A', 53)) return "images/achievements/53.png" },
			color: '#710CC4',
		},
		54: {
			name: 'That\'s no Particle no More',
			done() {return player.sp.points.gte(1000000)},
			tooltip: 'obtain 1,000,000 subatomic particles.',
			unlocked() { return hasAchievement('A', 53) },
			image() { if (hasAchievement('A', 54)) return "images/achievements/54.png" },
			color: '#710CC4',
		},
		55: {
			name: 'Anti Dark Matter',
			done() {return player.sp.points.gte(1e11)},
			tooltip: 'obtain 1e11 subatomic particles.',
			unlocked() { return hasAchievement('A', 54) },
			image() { if (hasAchievement('A', 55)) return "images/achievements/55.png" },
			color: '#710CC4',
		},
		56: {
			name: 'Hollow Particles',
			done() {return player.sp.points.gte(10) && getBuyableAmount('sp', 11).eq(0) && getBuyableAmount('sp', 12).eq(0) && getBuyableAmount('sp', 21).eq(0) && player.h.total.eq(0)},
			tooltip: 'obtain 10 subatomic particles with no subatomic particle rebuyables and hexes.',
			unlocked() { return hasAchievement('A', 52) && hasAchievement('A', 61) },
			image() { if (hasAchievement('A', 56)) return "images/achievements/56.png" },
			color: '#710CC4',
		},
		61: {
			name: 'The Hex Game',
			done() {return player.h.points.gte(1)},
			tooltip: 'obtain 1 hex.',
			unlocked() { return hasAchievement('A', 61) },
			image() { if (hasAchievement('A', 61)) return "images/achievements/61.png" },
			color: '#E36409',
		},
		62: {
			name: 'Cursed into Oblivion',
			done() {return player.h.points.gte(1e10)},
			tooltip: 'obtain 1e10 hexes.',
			unlocked() { return hasAchievement('A', 61) },
			image() { if (hasAchievement('A', 62)) return "images/achievements/62.png" },
			color: '#E36409',
		},
		63: {
			name: 'The Prophecy of Doom',
			done() {return player.h.points.gte(1e100)},
			tooltip: 'obtain 1e100 hexes.',
			unlocked() { return hasAchievement('A', 62) },
			image() { if (hasAchievement('A', 63)) return "images/achievements/63.png" },
			color: '#E36409',
		},
		64: {
			name: 'The Advent of the End',
			done() {return player.h.points.gte('1e1000')},
			tooltip: 'obtain 1e1000 hexes.',
			unlocked() { return hasAchievement('A', 63) },
			image() { if (hasAchievement('A', 64)) return "images/achievements/64.png" },
			color: '#E36409',
		},
		65: {
			name: 'Nihilism: Nothing is There',
			done() {return player.h.points.gte('1e10000')},
			tooltip: 'obtain 1e10,000 hexes.',
			unlocked() { return hasAchievement('A', 64) },
			image() { if (hasAchievement('A', 65)) return "images/achievements/65.png" },
			color: '#E36409',
		},
		66: {
			name: 'Same Old Tricks',
			done() {return player.h.points.gte(1e10) && getBuyableAmount('c', 11).eq(0) && getBuyableAmount('c', 12).eq(0) && player.sp.total.eq(0)},
			tooltip: 'obtain 1e10 hexes with no subatomic particles and core rebuyables.',
			unlocked() { return hasAchievement('A', 62) && hasAchievement('A', 71) },
			image() { if (hasAchievement('A', 66)) return "images/achievements/66.png" },
			color: '#E36409',
		},
		71: {
			name: 'Demon Spirits',
			done() {return player.ds.points.gte(1)},
			tooltip: 'obtain 1 demon soul.',
			unlocked() { return hasAchievement('A', 71) },
			image() { if (hasAchievement('A', 71)) return "images/achievements/71.png" },
			color: '#BA0035',
		},
		72: {
			name: 'Demonic Ruin',
			done() {return player.ds.points.gte(1e8)},
			tooltip: 'obtain 1e8 demon souls.',
			unlocked() { return hasAchievement('A', 71) },
			image() { if (hasAchievement('A', 72)) return "images/achievements/72.png" },
			color: '#BA0035',
		},
		73: {
			name: 'Demon Summoning',
			done() {return player.ds.points.gte(1e60)},
			tooltip: 'obtain 1e60 demon souls.',
			unlocked() { return hasAchievement('A', 72) },
			image() { if (hasAchievement('A', 73)) return "images/achievements/73.png" },
			color: '#BA0035',
		},
		74: {
			name: 'Demonic Origin',
			done() {return player.ds.points.gte('1e400')},
			tooltip: 'obtain 1e400 demon souls.',
			unlocked() { return hasAchievement('A', 73) },
			image() { if (hasAchievement('A', 74)) return "images/achievements/74.png" },
			color: '#BA0035',
		},
		75: {
			name: 'Demonic Dimension',
			done() {return player.ds.points.gte('1e2000')},
			tooltip: 'obtain 1e2000 demon souls.',
			unlocked() { return hasAchievement('A', 74) },
			image() { if (hasAchievement('A', 75)) return "images/achievements/75.png" },
			color: '#BA0035',
		},
		76: {
			name: 'Occult Uprising',
			done() {return player.ds.points.gte(1e10) && getBuyableAmount('ds', 11).eq(0) && player.a.total.eq(0)},
			tooltip: 'obtain 1e10 demon souls with no demon soul rebuyables and atoms.',
			unlocked() { return hasAchievement('A', 72) && hasAchievement('A', 81) },
			image() { if (hasAchievement('A', 76)) return "images/achievements/76.png" },
			color: '#BA0035',
		},
		81: {
			name: 'Atomic Mass',
			done() {return player.a.points.gte(1)},
			tooltip: 'obtain 1 atom.',
			unlocked() { return hasAchievement('A', 81) },
			image() { if (hasAchievement('A', 81)) return "images/achievements/81.png" },
			color: '#4D2FE0',
		},
		82: {
			name: 'Atomic Movement',
			done() {return player.a.points.gte(10)},
			tooltip: 'obtain 10 atoms.',
			unlocked() { return hasAchievement('A', 81) },
			image() { if (hasAchievement('A', 82)) return "images/achievements/82.png" },
			color: '#4D2FE0',
		},
		83: {
			name: 'Masses of Atoms',
			done() {return player.a.points.gte(1000)},
			tooltip: 'obtain 1,000 atoms.',
			unlocked() { return hasAchievement('A', 82) },
			image() { if (hasAchievement('A', 83)) return "images/achievements/83.png" },
			color: '#4D2FE0',
		},
		84: {
			name: 'Atom Dance',
			done() {return player.a.points.gte(10000)},
			tooltip: 'obtain 10,000 atoms.',
			unlocked() { return hasAchievement('A', 83) },
			image() { if (hasAchievement('A', 84)) return "images/achievements/84.png" },
			color: '#4D2FE0',
		},
		85: {
			name: 'Atomic Hole',
			done() {return player.a.points.gte(1e9)},
			tooltip: 'obtain 1e9 atoms.',
			unlocked() { return hasAchievement('A', 84) },
			image() { if (hasAchievement('A', 85)) return "images/achievements/85.png" },
			color: '#4D2FE0',
		},
		86: {
			name: 'For Science!',
			done() {return player.a.points.gte(10) && player.ds.total.eq(0)},
			tooltip: 'obtain 10 atoms with no demon souls.',
			unlocked() { return hasAchievement('A', 82) && hasAchievement('A', 91) },
			image() { if (hasAchievement('A', 86)) return "images/achievements/86.png" },
			color: '#4D2FE0',
		},
		91: {
			name: 'Praise the Lord',
			done() {return player.p.points.gte(1)},
			tooltip: 'obtain 1 prayer.',
			unlocked() { return hasAchievement('A', 91) },
			image() { if (hasAchievement('A', 91)) return "images/achievements/91.png" },
			color: '#FDBBFF',
		},
		92: {
			name: 'Church Prayer Circle',
			done() {return player.p.points.gte(1e10)},
			tooltip: 'obtain 1e10 prayers.',
			unlocked() { return hasAchievement('A', 91) },
			image() { if (hasAchievement('A', 92)) return "images/achievements/92.png" },
			color: '#FDBBFF',
		},
		93: {
			name: 'Prayers all around',
			done() {return player.p.points.gte(1e100)},
			tooltip: 'obtain 1e100 prayers.',
			unlocked() { return hasAchievement('A', 92) },
			image() { if (hasAchievement('A', 93)) return "images/achievements/93.png" },
			color: '#FDBBFF',
		},
		94: {
			name: 'Global Prayers',
			done() {return player.p.points.gte('1e1000')},
			tooltip: 'obtain 1e1000 prayers.',
			unlocked() { return hasAchievement('A', 93) },
			image() { if (hasAchievement('A', 94)) return "images/achievements/94.png" },
			color: '#FDBBFF',
		},
		95: {
			name: 'Everything is Prayers',
			done() {return player.p.points.gte('1e10000')},
			tooltip: 'obtain 1e10,000 prayers.',
			unlocked() { return hasAchievement('A', 94) },
			image() { if (hasAchievement('A', 95)) return "images/achievements/95.png" },
			color: '#FDBBFF',
		},
		96: {
			name: 'Persistence',
			done() {return player.p.points.gte(1e10) && player.h.total.eq(0) && player.sp.total.eq(0) && player.s.total.eq(0)},
			tooltip: 'obtain 1e10 prayers with no hexes, subatomic particles, and sanctums.',
			unlocked() { return hasAchievement('A', 92) && hasAchievement('A', 101) },
			image() { if (hasAchievement('A', 96)) return "images/achievements/96.png" },
			color: '#FDBBFF',
		},
		101: {
			name: 'Church Sanctum',
			done() {return player.s.points.gte(1)},
			tooltip: 'obtain 1 sanctum.',
			unlocked() { return hasAchievement('A', 101) },
			image() { if (hasAchievement('A', 101)) return "images/achievements/101.png" },
			color: '#AAFF00',
		},
		102: {
			name: 'Shrine Blessings',
			done() {return player.s.points.gte(10)},
			tooltip: 'obtain 10 sanctums.',
			unlocked() { return hasAchievement('A', 101) },
			image() { if (hasAchievement('A', 102)) return "images/achievements/102.png" },
			color: '#AAFF00',
		},
		103: {
			name: 'Greater Sanctum',
			done() {return player.s.points.gte(100)},
			tooltip: 'obtain 100 sanctums.',
			unlocked() { return hasAchievement('A', 102) },
			image() { if (hasAchievement('A', 103)) return "images/achievements/103.png" },
			color: '#AAFF00',
		},
		104: {
			name: 'The World is Sanctum',
			done() {return player.s.points.gte(1000)},
			tooltip: 'obtain 1,000 sanctums.',
			unlocked() { return hasAchievement('A', 103) },
			image() { if (hasAchievement('A', 104)) return "images/achievements/104.png" },
			color: '#AAFF00',
		},
		105: {
			name: 'Sanctum, Absolute',
			done() {return player.s.points.gte(10000)},
			tooltip: 'obtain 10,000 sanctums.',
			unlocked() { return hasAchievement('A', 104) },
			image() { if (hasAchievement('A', 105)) return "images/achievements/105.png" },
			color: '#AAFF00',
		},
		106: {
			name: 'Still Sanctum',
			done() {return player.s.points.gte(10) && player.ds.total.eq(0) && player.a.total.eq(0)},
			tooltip: 'obtain 10 sanctums with no demon souls and atoms.',
			unlocked() { return hasAchievement('A', 102) && hasAchievement('A', 111) },
			image() { if (hasAchievement('A', 106)) return "images/achievements/106.png" },
			color: '#AAFF00',
		},
		111: {
			name: 'Ancient Relic',
			done() {return player.r.points.gte(1)},
			tooltip: 'obtain 1 relic.',
			unlocked() { return hasAchievement('A', 111) },
			image() { if (hasAchievement('A', 111)) return "images/achievements/111.png" },
			color: '#B9A975',
		},
		112: {
			name: 'Giant Relics',
			done() {return player.r.points.gte(10)},
			tooltip: 'obtain 10 relics.',
			unlocked() { return hasAchievement('A', 111) },
			image() { if (hasAchievement('A', 112)) return "images/achievements/112.png" },
			color: '#B9A975',
		},
		113: {
			name: 'Treasure Hoard',
			done() {return player.r.points.gte(100)},
			tooltip: 'obtain 100 relics.',
			unlocked() { return hasAchievement('A', 112) },
			image() { if (hasAchievement('A', 113)) return "images/achievements/113.png" },
			color: '#B9A975',
		},
		114: {
			name: 'Mountain of Relics',
			done() {return player.r.points.gte(1000)},
			tooltip: 'obtain 1,000 relics.',
			unlocked() { return hasAchievement('A', 113) },
			image() { if (hasAchievement('A', 114)) return "images/achievements/114.png" },
			color: '#B9A975',
		},
		115: {
			name: 'Dragon\'s Hoard',
			done() {return player.r.points.gte(10000)},
			tooltip: 'obtain 10,000 relics.',
			unlocked() { return hasAchievement('A', 114) },
			image() { if (hasAchievement('A', 115)) return "images/achievements/115.png" },
			color: '#B9A975',
		},
		116: {
			name: 'Broken Relics',
			done() {return player.r.points.gte(10) && player.m.total.eq(0)},
			tooltip: 'obtain 10 relics with no molecules.',
			unlocked() { return hasAchievement('A', 112) && hasAchievement('A', 121) },
			image() { if (hasAchievement('A', 116)) return "images/achievements/116.png" },
			color: '#B9A975',
		},
		121: {
			name: 'Atom Combination',
			done() {return player.m.points.gte(1)},
			tooltip: 'obtain 1 molecule.',
			unlocked() { return hasAchievement('A', 121) },
			color: '#00CCCC',
		},
		122: {
			name: 'Varied Molecules',
			done() {return player.m.points.gte(1000000)},
			tooltip: 'obtain 1,000,000 molecules.',
			unlocked() { return hasAchievement('A', 121) },
			color: '#00CCCC',
		},
		123: {
			name: 'Molecule Dictionary',
			done() {return player.m.points.gte(1e12)},
			tooltip: 'obtain 1e12 molecules.',
			unlocked() { return hasAchievement('A', 122) },
			color: '#00CCCC',
		},
		124: {
			name: 'Plethora of Molecules',
			done() {return player.m.points.gte(1e25)},
			tooltip: 'obtain 1e25 molecules.',
			unlocked() { return hasAchievement('A', 123) },
			color: '#00CCCC',
		},
		125: {
			name: 'Molecules are Everything',
			done() {return player.m.points.gte(1e75)},
			tooltip: 'obtain 1e75 molecules.',
			unlocked() { return hasAchievement('A', 124) },
			color: '#00CCCC',
		},
		126: {
			name: 'Shiny New Molecules',
			done() {return player.m.points.gte(1000000) && player.r.total.eq(0)},
			tooltip: 'obtain 1,000,000 molecules with no relics.',
			unlocked() { return hasAchievement('A', 122) && hasAchievement('A', 131) },
			color: '#00CCCC',
		},
		131: {
			name: 'Spread the Word',
			done() {return player.gi.points.gte(1)},
			tooltip: 'obtain 1 good influence.',
			unlocked() { return hasAchievement('A', 131) },
			color: '#08FF87',
		},
		132: {
			name: 'Good Deeds All Around',
			done() {return player.gi.points.gte(10)},
			tooltip: 'obtain 10 good influence.',
			unlocked() { return hasAchievement('A', 131) },
			color: '#08FF87',
		},
		133: {
			name: 'World of Good',
			done() {return player.gi.points.gte(100)},
			tooltip: 'obtain 100 good influence.',
			unlocked() { return hasAchievement('A', 132) },
			color: '#08FF87',
		},
		134: {
			name: 'Maximum Good',
			done() {return player.gi.points.gte(1000)},
			tooltip: 'obtain 1,000 good influence.',
			unlocked() { return hasAchievement('A', 133) },
			color: '#08FF87',
		},
		135: {
			name: 'Good Exceeding',
			done() {return player.gi.points.gte(10000)},
			tooltip: 'obtain 10,000 good influence.',
			unlocked() { return hasAchievement('A', 134) },
			color: '#08FF87',
		},
		136: {
			name: 'Science is not Holy',
			done() {return player.gi.points.gte(10) && player.m.total.eq(0)},
			tooltip: 'obtain 10 good influence with no molecules.',
			unlocked() { return hasAchievement('A', 132) && hasAchievement('A', 151) },
			color: '#08FF87',
		},
		141: {
			name: 'Malevolent Evil',
			done() {return player.ei.points.gte(1)},
			tooltip: 'obtain 1 evil influence.',
			unlocked() { return hasAchievement('A', 141) },
			color: '#FF4400',
		},
		142: {
			name: 'Evil Encroaches',
			done() {return player.ei.points.gte(10)},
			tooltip: 'obtain 10 evil influence.',
			unlocked() { return hasAchievement('A', 141) },
			color: '#FF4400',
		},
		143: {
			name: 'Evil Encompasses',
			done() {return player.ei.points.gte(100)},
			tooltip: 'obtain 100 evil influence.',
			unlocked() { return hasAchievement('A', 142) },
			color: '#FF4400',
		},
		144: {
			name: 'Invasion of Evil',
			done() {return player.ei.points.gte(1000)},
			tooltip: 'obtain 1,000 evil influence.',
			unlocked() { return hasAchievement('A', 143) },
			color: '#FF4400',
		},
		145: {
			name: 'Evil to Infinity',
			done() {return player.ei.points.gte(10000)},
			tooltip: 'obtain 10,000 evil influence.',
			unlocked() { return hasAchievement('A', 144) },
			color: '#FF4400',
		},
		146: {
			name: 'Disbelievers',
			done() {return player.ei.points.gte(10) && player.m.total.eq(0)},
			tooltip: 'obtain 10 evil influence with no molecules.',
			unlocked() { return hasAchievement('A', 142) && hasAchievement('A', 151) },
			color: '#FF4400',
		},
		151: {
			name: 'Big Fight',
			done() {return player.w.points.gte(1)},
			tooltip: 'obtain 1 war.',
			unlocked() { return hasAchievement('A', 151) },
			color: '#A0A0A0',
		},
		152: {
			name: '"Resolving Differences"',
			done() {return player.w.points.gte(10)},
			tooltip: 'obtain 10 wars.',
			unlocked() { return hasAchievement('A', 151) },
			color: '#A0A0A0',
		},
		153: {
			name: 'Ravaging War',
			done() {return player.w.points.gte(100)},
			tooltip: 'obtain 100 wars.',
			unlocked() { return hasAchievement('A', 152) },
			color: '#A0A0A0',
		},
		154: {
			name: 'War of the World',
			done() {return player.w.points.gte(1000)},
			tooltip: 'obtain 1,000 wars.',
			unlocked() { return hasAchievement('A', 153) },
			color: '#A0A0A0',
		},
		156: {
			name: 'Just Pure War',
			done() {return player.w.points.gte(10) && player.m.total.eq(0) && player.ch.total.eq(0)},
			tooltip: 'obtain 10 wars with no molecules and chaos.',
			unlocked() { return hasAchievement('A', 152) && hasAchievement('A', 171) },
			color: '#FF4400',
		},
		161: {
			name: 'Life is Born',
			done() {return player.cl.points.gte(1)},
			tooltip: 'obtain 1 cellular life.',
			unlocked() { return hasAchievement('A', 161) },
			color: '#008800',
		},
		162: {
			name: 'Life Blossoms',
			done() {return player.cl.points.gte(100)},
			tooltip: 'obtain 100 cellular life.',
			unlocked() { return hasAchievement('A', 161) },
			color: '#008800',
		},
		163: {
			name: 'Many Cells',
			done() {return player.cl.points.gte(10000)},
			tooltip: 'obtain 10,000 cellular life.',
			unlocked() { return hasAchievement('A', 162) },
			color: '#008800',
		},
		164: {
			name: 'Congealing Cells',
			done() {return player.cl.points.gte(1000000)},
			tooltip: 'obtain 1,000,000 cellular life.',
			unlocked() { return hasAchievement('A', 163) },
			color: '#008800',
		},
		166: {
			name: 'Life At Peace',
			done() {return player.cl.points.gte(100) && player.w.total.eq(0) && player.ch.total.eq(0)},
			tooltip: 'obtain 100 cellular life with no wars and chaos.',
			unlocked() { return hasAchievement('A', 162) && hasAchievement('A', 171) },
			color: '#FF4400',
		},
		171: {
			name: 'Rising Chaos',
			done() {return player.ch.points.gte(1)},
			tooltip: 'obtain 1 chaos.',
			unlocked() { return hasAchievement('A', 171) },
			color: '#FFFFFF',
		},
		172: {
			name: 'Madness of Chaos',
			done() {return player.ch.points.gte(10)},
			tooltip: 'obtain 10 chaos.',
			unlocked() { return hasAchievement('A', 171) },
			color: '#FFFFFF',
		},
		173: {
			name: 'Chaos Engulfs',
			done() {return player.ch.points.gte(100)},
			tooltip: 'obtain 100 chaos.',
			unlocked() { return hasAchievement('A', 172) },
			color: '#FFFFFF',
		},
	},
});
